### ISSUE TITLE
No connection between Dres and landed RA-100 on Kerbin ("Homemade DSN")

### ISSUE THREAD

**Issue by rockfactory** [Kerbalight/CommNext#5]
> But still, the DSN and my vessel in Dres's orbit aren't connecting. In the screen: orange circle = DSN I just launched, red circle = my vessel in Dres orbit. They aren't connected. There's no occlusion I'm aware of, they're looking at each other without anything between them.

![Image](https://github.com/Kerbalight/CommNext/assets/112330494/030c82be-fb79-4c49-9f0f-2253b08f1bda)

> Here's one of the saves from a bit later after I wrote that. I launched a new DSN because that first one was a bit embarrassing to look at. It's landed on top of the VAB, with dirrect line of sight to Dres. Vessel "Eye of Destiny" is in orbit around Dres and also with a direct line of sight to Kerbin. Kerbin's DSN shows in orange, but Dres's vessel is in red, no connection.

Reported by @Falki-git

[quicksave_481.json](https://github.com/Kerbalight/CommNext/files/14272950/quicksave_481.json)

**Comment by Falki-git** [comment]
Ok, so for my Dres occlusion bug, it DOES work now with 0.4.1 (yay!), however with a weird behaviour. When you first load a save I sent you, it won't be connect, same as before. Then when you EVA a kerbal it then connects. When he reenters again, it's still connected. So it's as if something gets triggered when he first leaves the vessel. Overall nice update!

**Comment by rockfactory** [comment]
In the end, it was due to Kerbin occluding the connection, I'll upload the video with new Vessel Comms Report explaining the situation. However we've got new tools, so thanks @Falki-git !
