### ISSUE TITLE
QoL request: persist app tray position

### ISSUE THREAD

**Issue by Falki-git** [Kerbalight/CommNext#8]
Either in save game files or somewhere else. I'd like to move the tray to the top left and not have to reposition it again.

![CommNextTrayPositionPersist](https://github.com/Kerbalight/CommNext/assets/72734856/1cecae3b-3864-4132-ae74-a6ae64de4157)

**Comment by rockfactory** [comment]
Thanks @Falki-git ! Should be working in v0.5.2

**Comment by Falki-git** [comment]
Nice, thanks!
